[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_escrow = "4zgcxLfmTTg1fKhjnM6Ps9eFnYavXspSAFSoKoXDpesB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/varsha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



